### ISSUE TITLE
Not support mouse buttons like VK_XBUTTON1, VK_XBUTTON2, VK_LBUTTON, VK_RBUTTON, VK_MBUTTON

### ISSUE THREAD

**Issue by liaoliao666** [amrbashir/global-hotkey#102]

**Comment by amrbashir** [comment]
This is not supported by the Windows OS. What is your use-case exactly? and is there some other framework or an application that provides this?

**Comment by lucascompython** [comment]
Hi there, I'm not the original creator of this issue, but I wanted to share my use case.

I'm building an app where users visually define macros through a node-based UI.

The app itself uses a small library I wrote which currently wraps `tauri-global-hotkey` for listening to events and `enigo` for emitting events in a cross-platform way. I intend on further developing this library because there currently aren't many well-maintained, cross-platform GUI automation libraries.

One feature I want to implement is macro recording, where the user performs actions and the app records them so they can later be reused as a macro. For this, I would need support for listening to mouse events, including mouse buttons and mouse movement.

Since I'm already using Tauri and the Tauri ecosystem, it would be great to keep all input event handling in the same place instead of relying on multiple separate libraries.

> and is there some other framework or application that provides this?

There is `rdev`: https://github.com/Narsil/rdev

I'd also be willing to help implement this functionality if the maintainers think it fits the scope of the crate.

**Comment by FabianLars** [comment]
global-hotkey is a hotkey crate using the special OS hotkey apis. in my opinion, using a global key listener (rdev) sounds out of scope for me there. It also has a bunch of issues and limitations (e.g. no wayland support, requiring special perms on macos)

**Comment by lucascompython** [comment]
That makes sense.

I initially assumed global hotkeys were internally implemented through a global input listener + key combination matching.

And just to clarify, I wasn't proposing using `rdev` internally in `global-hotkey`, I only mentioned it as an example of a crate that already implements global input listening.

For my use case, the missing part is mainly mouse/input recording functionality for macro recording.

Also, regarding `rdev`, I think the documentation may be somewhat outdated since the repository appears to contain some Wayland related implementation work already. I tested the current Wayland implementation locally, and it seemed to work fine in my testing, although I haven't done extensive cross-desktop/compositor testing yet.

I think it might make more sense for me to just use `rdev` for listening to mouse events and keep `global-hotkey` for everything else.
Thanks
