### ISSUE TITLE
Support separate keydown/keyup event for hotkey

### ISSUE THREAD

**Issue by morajabi** [amrbashir/global-hotkey#9]
Is this possible to do? I've seen this in Swift before.

Here it is implemented for macOS: https://medium.com/@avaidyam/building-a-better-registereventhotkey-900afd68f11f but seems to be a lot more than that lol.

**Comment by amrbashir** [comment]
I think this maybe be possible on Linux(X11) and maybe Windows too (I have an idea but haven't tested it yet).

As for macOS, I see in the article that they are using private APIs which will result in your app getting rejected by The App Store so we can't use that. Since I am not a macOS dev, I will have to leave it to someone else to contribute.

**Comment by morajabi** [comment]
I see in the macOS ffi impl we have `kEventHotKeyPressed`. Is there a reason `kEventHotKeyReleased` wouldn't work?
(I've seen it used in the wild: https://github.com/cocoabits/MASShortcut/pull/114/files#diff-bd9e25dca147d4385ffb9cc5e3766ae2051e1532203cebc902777a27a880e02fR21)

It is useful for creating a "hold to talk" interaction for our users. Happy to make a PR for macOS if the API is decided upon.

**Comment by amrbashir** [comment]
@morajabi thanks for looking into this, the API should be straight forward, you would need to just add a field in `GlobalHotKeyEvent` 
```rs
pub enum HotKeyState {
	Pressed,
	Released,
}

pub struct GlobalHotKeyEvent {
    /// Id of the associated [`HotKey`]
    pub id: u32,
	pub state: HotKeyState,
}
```

**Comment by Megamannen** [comment]
+1 on this
